### PR TITLE
174 Notification Wording

### LINKED ISSUE #174: Notification Wording
Low priority. Tested with Sparrow 1.5.0.

Change: "Branta: Sparrow Failed Verification" - to reuse: https://github.com/BrantaOps/branta-windows/blob/main/Branta/Resources/StringResources.xaml#L62

This will match mac behavior - the alert should match the table.

Screen Shot 2024-05-27 at 8 33 13 PM
Screen Shot 2024-05-27 at 8 33 22 PM

### PR DESCRIPTION
**Pull request by kylemccullen**
Closes #174

### CODE REVIEW

File: Branta/Commands/VerifyWalletsCommand.cs [hunk 1]
```diff
@@ -48,17 +52,29 @@ public override void Execute(object parameter)
 
             viewModel.AddWallet(wallet);
 
-            if (wallet.Status != WalletStatus.Verified &&
-                wallet.Status != WalletStatus.NotFound &&
-                previousWalletStatus.GetValueOrDefault(walletType.Name, WalletStatus.Verified) == WalletStatus.Verified &&
-                _settings.WalletVerification.WalletStatusChangeEnabled)
+            if (!_settings.WalletVerification.WalletStatusChangeEnabled)
```
Comment (kylemccullen) [inline Branta/Commands/VerifyWalletsCommand.cs:55]: The logic here is as follows
 * If users have disabled WalletStatusChange notifications then don't display the notification
 * On the first run, don't display a notification for Verified or Not Found statuses
 * Only display a notification if the current wallet status is different than the previous wallet status

**Review by keith-gardner — APPROVED** [review]
