### PR TITLE
144 Sync Wallet Statuses across platforms

### LINKED ISSUE #144: Sync Wallet Statuses across platforms
* Verified
    * Wallet install found and hash matches
  * Not Verified
    * Wallet install found, hash does not match
  * Version Too New
  * Version Too Old
  * Version Not Supported
    * Version not found in CheckSum list
  * Installation Not Found
    * No wallet installed at known directory 
  * Installing
  * BrantaError
    * Exception occurred while processing

### PR DESCRIPTION
**Pull request by kylemccullen**
Closes #144

### CODE REVIEW

File: Branta/Classes/FileStorage.cs [hunk 1]
```diff
@@ -19,12 +19,14 @@ public static async Task SaveAsync(string path, string content)
 
     public static async Task<string> LoadAsync(string path)
     {
+        path = GetFullPath(path);
```
Comment (keith-gardner) [inline Branta/Classes/FileStorage.cs:22]: One open question on mac is:
Can admin & guest accounts access the api files?
Added: https://github.com/BrantaOps/branta-mac/issues/135

Comment (keith-gardner) [reply Branta/Classes/FileStorage.cs:22]: Closed the above issue. Everything functional 👍
